#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

diff <(${SCRIPT_DIR}/../docs/src/make_md.py ${SCRIPT_DIR}/../docs/src/README.md) <(cat ${SCRIPT_DIR}/../README.md) \
&& \
diff <(${SCRIPT_DIR}/../docs/src/make_md.py docs/src/docs/ProgrammersGuide.md) <(cat ${SCRIPT_DIR}/../docs/ProgrammersGuide.md) 

