/*
MIT License

Copyright (c) 2022-2026 Richard Powell

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// This file is AUTO-GENERATED by scripts/update-version.sh
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To update version: create a new git tag (e.g., git tag v1.2.3)
// and run: ./scripts/update-version.sh

#pragma once

namespace wxUI {

// clang-format off
#define WXUI_VERSION_MAJOR 0
#define WXUI_VERSION_MINOR 3
#define WXUI_VERSION_PATCH 0
#define WXUI_VERSION_TWEAK 0
#define WXUI_VERSION_STRING "0.3.0"
// clang-format on

    struct Version {
        static constexpr int major = WXUI_VERSION_MAJOR;
        static constexpr int minor = WXUI_VERSION_MINOR;
        static constexpr int patch = WXUI_VERSION_PATCH;
        static constexpr int tweak = WXUI_VERSION_TWEAK;
        static constexpr const char* string = WXUI_VERSION_STRING;
    };

    inline constexpr Version version{};

} // namespace wxUI
