#!/bin/bash
# Copyright (c) 2025 Richard Powell
#
# Updates include/wxUI/version.hpp from the latest git tag or specified version
# This script can be run manually or automatically via git hooks
#
# Usage: 
#   ./update-version.sh         # Use latest git tag
#   ./update-version.sh v1.2.3  # Use specified version

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_FILE="$PROJECT_ROOT/include/wxUI/version.hpp"

# Check if version was provided as argument
if [ $# -eq 1 ]; then
    VERSION_TAG="$1"
    # Strip 'v' prefix if present
    VERSION="${VERSION_TAG#v}"
    echo "Using specified version: $VERSION"
else
    # Extract version from git tags
    if command -v git &> /dev/null && git rev-parse --git-dir &> /dev/null 2>&1; then
        VERSION_TAG=$(git describe --tags --match "v[0-9]*" --abbrev=0 2>/dev/null || echo "v0.1.0")
        VERSION=${VERSION_TAG#v}  # Remove leading 'v'
        echo "Using version from git tag: $VERSION (tag: $VERSION_TAG)"
    else
        VERSION="0.1.0"
        VERSION_TAG="v0.1.0"
        echo "Warning: git not available or not in a git repository, using default version $VERSION"
    fi
fi

# Parse version components
IFS='.' read -r MAJOR MINOR PATCH TWEAK <<< "$VERSION"
MINOR=${MINOR:-0}
PATCH=${PATCH:-0}
TWEAK=${TWEAK:-0}

# Generate version.hpp with embedded LICENSE.md
{
    echo "/*"
    cat "$PROJECT_ROOT/LICENSE.md"
    echo "*/"
    cat << 'HEADER'
// This file is AUTO-GENERATED by scripts/update-version.sh
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To update version: create a new git tag (e.g., git tag v1.2.3)
// and run: ./scripts/update-version.sh

#pragma once
HEADER
    cat << EOF

namespace wxUI {

// clang-format off
#define WXUI_VERSION_MAJOR ${MAJOR}
#define WXUI_VERSION_MINOR ${MINOR}
#define WXUI_VERSION_PATCH ${PATCH}
#define WXUI_VERSION_TWEAK ${TWEAK}
#define WXUI_VERSION_STRING "${VERSION}"
// clang-format on

    struct Version {
        static constexpr int major = WXUI_VERSION_MAJOR;
        static constexpr int minor = WXUI_VERSION_MINOR;
        static constexpr int patch = WXUI_VERSION_PATCH;
        static constexpr int tweak = WXUI_VERSION_TWEAK;
        static constexpr const char* string = WXUI_VERSION_STRING;
    };

    inline constexpr Version version{};

} // namespace wxUI
EOF
} > "$VERSION_FILE"

echo "Successfully updated $VERSION_FILE"
