name: Copyright Check

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  copyright-check:
    name: Copyright Check
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: check
      run: ${{github.workspace}}/checklists/check_copyright

    - name: check
      run: ${{github.workspace}}/checklists/check_md

