# wxWidgets 3.2.x Windows Compatibility Testing

name: wxWidgets 3.2.x Windows

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'test-compat-*'  # Allow testing on branches named test-compat-*
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  test-3-2-x:
    name: wxWidgets 3.2.x Tests
    uses: ./.github/workflows/wxwidgets_compat_reusable.yml
    with:
      wxwidgets_versions: '["v3.2.10"]'
      os: '["windows"]'
      workflow_name: 'wxWidgets 3.2.x Window'
